# File: .github/workflows/ci.yml
name: Java CI with Maven

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Sets up JDK 21 for you to use in your workflow
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      # Step 3: Runs the Maven command to build the project and run tests
      - name: Build and test with Maven
        run: mvn -B clean package        git push git@github.com:${{ github.repository }} HEAD:main
