
name: CI/CD Build & Deploy (SSH)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Set up SSH Access ---
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # --- Checkout code ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Set up Java (JDK 21) ---
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # --- Build with Maven ---
      - name: Build project
        run: mvn -B clean package

      # --- Run tests ---
      - name: Run tests
        run: mvn test

      # --- Configure Git & Push Artifacts ---
      - name: Push build artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Use SSH remote
          git remote set-url origin git@github.com:${{ github.repository }}

          # Add and commit JARs or generated files
          git add target/*.jar || echo "No JARs found to add"
          git commit -m "Add build artifacts [skip ci]" || echo "No changes to commit"

          # Push via SSH
          git push origin HEAD:main
         git push git@github.com:${{ github.repository }} HEAD:main
